import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../globals.css";
import Header from "@/components/Header";
import { ClerkProvider } from "@clerk/nextjs";
import Footer from "@/components/Footer";
import Toaster from "@/components/Toaster";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "block",
});

export const metadata: Metadata = {
  title: "Blue Berry",
  description: "Generated by create next app Ecommerce Website Blue Berry",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider dynamic>
      <html lang="en">
        <body
          className={`${poppins.className} antialiased`}
        >
          <Header />
          {children}
          <Footer />
          <Toaster position="bottom-right" toastOptions={{
            style: {
              background: "#000000",
              color: "#ffffff"
            }
          }} />
        </body>
      </html>
    </ClerkProvider>
  );
}
