import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Ecommerce Blue Berry",
    description: "Generated by create next app Ecommerce Website Blue Berry",
};

export default function StusioLayout({ children }: { children: React.ReactNode }) {
    return (
        <div>
            {children}
        </div>
    );
}