import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Ecommerce Blue Berry",
    description: "Generated by create next app Ecommerce Website Blue Berry",
};

export default function Layout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                {children}
            </body>
        </html>
    );
}